### ISSUE TITLE
【建議】回到上一頁的定點，能否不是片尾的申請演示?

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-official#6]
step1.從「網頁中的按鈕」連結到其他頁面
![image](https://user-images.githubusercontent.com/41721950/63395480-798a7900-c3f6-11e9-8aea-cdee7c31f9fe.png)
step2.點選『上一頁』
![image](https://user-images.githubusercontent.com/41721950/63395905-e2bebc00-c3f7-11e9-90f8-0e2beba23329.png)
問題：直接跳上一頁的『申請演示』
![image](https://user-images.githubusercontent.com/41721950/63395958-0da91000-c3f8-11e9-9922-8195cb6c2ed4.png)
若非從按鈕連結到其他頁面，按上一頁會回到頁首；若不能回到上一頁的『按鈕』位置，建議至少是相同的使用者體驗-回到頁首。
以上建議請參考，感恩~

**Comment by ryuichl** [comment]
恩 應該是要回到最上面
